name: learn-github-actions
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > .npmrc
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
      - name: success label
        if: success()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: success
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: failure
      - name: fail label
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: failure